version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: keypilot-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID

  gateway-service:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: keypilot-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - APP_NAME=keypilot-gateway
      - APP_VERSION=1.0.0
      - REDIS_URL=redis://redis:6379
      # Security headers
      - SESSION_SECRET=your-super-secret-session-key-change-this
      - JWT_SECRET=your-jwt-secret-key-change-this
      - ENCRYPTION_KEY=your-32-char-encryption-key-here
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./logs:/usr/src/app/logs:Z
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "scripts/health-check.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
      - /usr/src/app/logs:noexec,nosuid,size=100m

  gateway-service-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: keypilot-gateway-dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - DEMO_USERS=demo1:pass1,demo2:pass2,demo3:pass3
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/usr/src/app:Z
      - /usr/src/app/node_modules
      - ./logs:/usr/src/app/logs:Z
    restart: unless-stopped
    profiles:
      - dev
    security_opt:
      - no-new-privileges:true

volumes:
  redis_data:
    driver: local
